### ISSUE TITLE
Any journal references available for this implementation?

### ISSUE THREAD

**Issue by Gowresh7** [Alpaca-zip/ultralytics_ros#14]
Hello,

This really a great work. 
I would like to understand the background of it, especially the projection of the pointcloud to the 2d image space and conversion of the 2d detection pixels to 3d coordinates. Is there any journal or article that you referred to?

**Comment by Alpaca-zip** [comment]
Thank you @Gowresh7 for your valuable report!

> I would like to understand the background of it, especially the projection of the pointcloud to the 2d image space and conversion of the 2d detection pixels to 3d coordinates. Is there any journal or article that you referred to?

I have not written a paper on this program myself. However, there are several programs and articles that I have referenced.
- http://wiki.ros.org/velo2cam_calibration
- https://github.com/beltransen/velo2cam_calibration
- https://ieeexplore.ieee.org/abstract/document/9733276

**Comment by Alpaca-zip** [comment]
Was the information I provided sufficient? Feel free to re-open this issue if you have any more questions.

Thank you.
