### ISSUE TITLE
tracker_with_cloud_node not returnn 3D bounding box on topic /detection3d_result 

### ISSUE THREAD

**Issue by thetiennguyen** [Alpaca-zip/ultralytics_ros#34]
Dear Alpaca, 
Thank for you project, I am using your results. However, when I run for tracker_clound ... I can not get the value 3D bounding box of topic /detection3d_topic. Please check about your project this issue. Thank you so much. 
"Detected objects(3D bounding box) to detection3d_topic parameter. ([vision_msgs/Detection3DArray](http://docs.ros.org/en/lunar/api/vision_msgs/html/msg/Detection3DArray.html))"

**Comment by Ca11m3X** [comment]
> Dear Alpaca, Thank for you project, I am using your results. However, when I run for tracker_clound ... I can not get the value 3D bounding box of topic /detection3d_topic. Please check about your project this issue. Thank you so much. "Detected objects(3D bounding box) to detection3d_topic parameter. ([vision_msgs/Detection3DArray](http://docs.ros.org/en/lunar/api/vision_msgs/html/msg/Detection3DArray.html))"

Have you fixed this problem yet? I figured out that the program is stuck in "ec.extract(cluster_indices);" in cpp node.

**Comment by Alpaca-zip** [comment]
Thank you @thetiennguyen , @Ca11m3X   for your valuable report.

Currently, I am too busy to work on this issue. However, I will check and get back to you shortly after 7 December.

> Have you fixed this problem yet? I figured out that the program is stuck in "ec.extract(cluster_indices);" in cpp node.

Are there any error messages or other outputs?

Thank you.

**Comment by Ca11m3X** [comment]
> Thank you @thetiennguyen , @Ca11m3X for your valuable report.
> 
> Currently, I am too busy to work on this issue. However, I will check and get back to you shortly after 7 December.
> 
> > Have you fixed this problem yet? I figured out that the program is stuck in "ec.extract(cluster_indices);" in cpp node.
> 
> Are there any error messages or other outputs?
> 
> Thank you.

There are not any error messages. For particularly, "stuck in "ec.extract(cluster_indices);"" means that the program take a lot of time to execute this function. If I reduce the "max_cluster_size" to 300, the 3D bounding box will appear in rviz but it is not correctly. That is the point I want to report.
In addition, Can you share about your computer configuration when you run this program. For me, my laptop is Precision 7510, 16Gb ram, GPU Quadro m1000m 2Gb.

I appreciate your work for the community.

**Comment by thetiennguyen** [comment]
Dear Alpaca and Ca11m3X,
Rightnow, I have not free time to do it follow Ca11m3X, I will try it soon
to check. In addition, My laptop is quite modern, I think it is enough to
run YOLOv8. Its configuration Dell Core i7 gen 12700H, 16 Gb Ram, GPU
Nvidia gerfoce 3050 4Gb

Vào Th 6, 1 thg 12, 2023 vào lúc 17:35 Ca11m3X ***@***.***>
đã viết:

**Comment by Alpaca-zip** [comment]
Dear @thetiennguyen and @Ca11m3X,

My laptop configuration is as follows.
- Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
- 16.0GB RAM
- NVIDIA GeForce RTX 2060
___
> For particularly, "stuck in "ec.extract(cluster_indices);"" means that the program take a lot of time to execute this function.

In [feature/downsample_cloud](https://github.com/Alpaca-zip/ultralytics_ros/tree/feature/downsample_cloud), I added a downsampling process to the point cloud that is passed to `EuclideanClusterExtraction`. This should allow bounding boxes to be extracted without significant loss of accuracy, even if the `max_cluster_size` is `300`. If this change is effective, I would like to refactor the contents of this branch and merge it into the main branch.

I would be happy to know the results of your trial.

Thank you.

**Comment by Ca11m3X** [comment]
Dear @Alpaca-zip and @thetiennguyen ,

Yesterday, I figured out the same solution (downsampling by using VoxelGrid) as you did. The problem is fixed.

I am a newbie in Point cloud processing, and I am very interested in this field😄. 

Thank you for the updating.

**Comment by Alpaca-zip** [comment]
The content of this issue in `noetic-devel` has been improved with https://github.com/Alpaca-zip/ultralytics_ros/pull/35.

If the 3D bounding box is not displayed correctly in `tracker_with_cloud_node`, please consider using a lighter yolo model(`yolov8n.pt`) or increasing the `voxel_leaf_size` parameter.

Thank you all for your support to the project.
___
**Tasks**
- [x] melodic-devel
- [x] noetic-devel

**Comment by thetiennguyen** [comment]
Thank for you answer, rightnow I run and get the 3D Bounding boxes ( with yolov8n.pt). Thanks a lot. In addition, I am studying PhD about robotics. I have a question whether I can contact to you via other social media such as facebook, telegram or ... something like that to discuss some interests. Thanks a lot

**Comment by Alpaca-zip** [comment]
Dear @thetiennguyen ,

You can find my twitter(X) account on my github profile. Please feel free to contact me.

Thank you.
