### ISSUE TITLE
fatal error: ultralytics_ros/YoloResult.h: No such file or directory

### ISSUE THREAD

**Issue by miao202** [Alpaca-zip/ultralytics_ros#41]
When I catkin_make. I was prompted with
fatal error: ultralytics_ros/YoloResult.h: No such file or directory. and I didn't find the YoloResult.h file, where is it please?

**Comment by Alpaca-zip** [comment]
Thank you @miao202 for your valuable report.

- In my case, the header file exists in the following directory:
`catkin_ws/devel/.private/ultralytics_ros/include/ultralytics_ros/YoloResult.h`

- Try adding `add_dependencies(tracker_with_cloud_node ultralytics_ros_generate_messages_cpp)` at line 77 of the following code snippet and rebuild to see if this helps.
https://github.com/Alpaca-zip/ultralytics_ros/blob/d15477f9620d7114cccc737e6629c3c830d757be/CMakeLists.txt#L70-L77
  
  **rebuild**
  ```bash
  $ cd {ROS_WORKSPACE} && rm -rf build/ devel/
  $ catkin_make
  ```

Thank you.

**Comment by Alpaca-zip** [comment]
If this issue is resolved, please let me know. I will create a Pull Request to address it.

**Comment by miao202** [comment]
> 如果此问题得到解决，请告诉我。我将创建一个 Pull Request 来解决这个问题。

Thank you very much, this issue has been resolved
