### ISSUE TITLE
How to detect camera information in real time

### ISSUE THREAD

**Issue by wyb17js** [Alpaca-zip/ultralytics_ros#45]
作者你好，我使用gazebo搭建了一个环境，并且在我的车体模型上安装了深度相机插件，我想实现识别结果以视频的形式展示出来，随着摄像头检测到画面的变化而不断变化，但是当我运行了readme里面指定的launch文件后，我只得到了一张识别结果图片，并且rviz显示无响应，当我关闭后控制台报错如图所示
![image](https://github.com/Alpaca-zip/ultralytics_ros/assets/148990128/27a5df8b-e96b-41cf-951f-65e0496bbe50)
我想知道我应该怎么配置或者编写launch文件才可以实现我想要的效果？还有我该怎么训练自己的模型？
![image](https://github.com/Alpaca-zip/ultralytics_ros/assets/148990128/1ac9bb2c-2de3-4b46-89f9-83171a453d04)

**Comment by Alpaca-zip** [comment]
Thank you @wyb17js , for asking your question.

> 我想知道我应该怎么配置或者编写launch文件才可以实现我想要的效果？

~~As it is difficult to solve this problem with the information you have provided, could you please share the scripts( e.g. gazebo configuration file) you are running?~~

> 还有我该怎么训练自己的模型？

I don't provide the functionality to train models directly in ROS/ROS 2. Please check the [Ultralytics YOLOv8 Docs link](https://docs.ultralytics.com/modes/train/) for more information.

Thank you.

**Comment by Alpaca-zip** [comment]
Dear @wyb17js,

I misunderstood your query earlier. Currently, the [humble-devel](https://github.com/Alpaca-zip/ultralytics_ros/tree/humble-devel) branch does not support 3D object detection using camera_info and point clouds. Please submit a feature request through this [link](https://github.com/Alpaca-zip/ultralytics_ros/issues/new?assignees=&labels=enhancement&projects=&template=feature-request.yml), and wait for it to be implemented. Alternatively, I recommend using ROS1.

Thank you.

**Comment by Alpaca-zip** [comment]
Announcement 📢
3D object detection using camera_info is now available in the [humble-devel](https://github.com/Alpaca-zip/ultralytics_ros/tree/humble-devel) branch. Please check it out!!

Thank you.
